
CREATE TABLE ANIMAL (
	CODIGOANIMAL INT NOT NULL,
	CODIGOCLIENTE INT NOT NULL,
	CODIGOUSUARIO INT NOT NULL,	
	CODIGOESPECIE INT NOT NULL,
	CODIGORACA INT NOT NULL,
	CODIGOPELAGEM INT NOT NULL,
	NOMEANIMAL VARCHAR(50) NOT NULL,
	FALECIDO INT,
	DATANASCIMENTO DATE NOT NULL,
	SEXO CHAR NOT NULL,
	PORTE CHAR(10) NOT NULL,	
	INATIVO INT NOT NULL, 
	DATACADASTRO DATETIME NOT NULL,
	FOTOANIMAL IMAGE, 
	OBSERVACOES VARCHAR (200),	
	CONSTRAINT PK_CODIGOANIMAL PRIMARY KEY (CODIGOANIMAL),
	CONSTRAINT FK_CODIGOCLIENTE FOREIGN KEY (CODIGOCLIENTE) REFERENCES CLIENTE(CODIGOCLIENTE),
	CONSTRAINT FK_CODIGOUSUARIO FOREIGN KEY (CODIGOUSUARIO) REFERENCES LOGIN(CODIGOUSUARIO),
	CONSTRAINT FK_CODIGOESPECIE FOREIGN KEY (CODIGOESPECIE) REFERENCES ESPECIE(CODIGOESPECIE),
	CONSTRAINT FK_CODIGOPELAGEM FOREIGN KEY (CODIGOPELAGEM) REFERENCES PELAGEM(CODIGOPELAGEM),
	CONSTRAINT FK_CODIGORACA FOREIGN KEY (CODIGORACA) REFERENCES RACA(CODIGORACA),
)

CREATE TABLE ESPECIE (
	CODIGOESPECIE INT NOT NULL,
	DESCRICAO VARCHAR(80) NOT NULL,
	CONSTRAINT PK_CODIGOESPECIE PRIMARY KEY (CODIGOESPECIE)
)

CREATE TABLE RACA (
	CODIGORACA INT NOT NULL,
	DESCRICAO VARCHAR(80) NOT NULL,
	CONSTRAINT PK_CODIGORACA PRIMARY KEY (CODIGORACA)
)

CREATE TABLE PELAGEM (
	CODIGOPELAGEM INT NOT NULL,
	DESCRICAO VARCHAR(80) NOT NULL,
	CONSTRAINT PK_PELAGEM PRIMARY KEY (CODIGOPELAGEM)
)

CREATE TABLE FUNCIONARIO (
	CODIGOFUNCIONARIO INT NOT NULL,
	CODIGOPESSOA INT NOT NULL, 
	CODIGOUSUARIO INT NOT NULL,
	CODIGOFUNCAO INT NOT NULL,
	CODIGOUSUARIOFUNCIONARIO INT NOT NULL,			
	CODIGOUNIDADE INT NOT NULL,
	DATACADASTRO DATETIME NOT NULL,
	DADOSADICIONAIS VARCHAR(200),
	CONSTRAINT PK_CODIGOFUNCIONARIO PRIMARY KEY (CODIGOFUNCIONARIO),
	CONSTRAINT FK_CODIGOPESSOA FOREIGN KEY (CODIGOPESSOA) REFERENCES PESSOA(CODIGOPESSOA),
	CONSTRAINT FK_CODIGOENDERECO FOREIGN KEY (CODIGOENDERECO) REFERENCES ENDERECO(CODIGOENDERECO),
	CONSTRAINT FK_CODIGOUSUARIOFUNCIONARIO FOREIGN KEY (CODIGOUSUARIOFUNCIONARIO) REFERENCES LOGIN(CODIGOUSUARIO),
	CONSTRAINT FK_CODIGOFUNCAO FOREIGN KEY (CODIGOFUNCAO) REFERENCES FUNCAO(CODIGOFUNCAO),
)

CREATE TABLE FUNCOES (
	CODIGOFUNCAO INT NOT NULL,
	CODIGOUSUARIO INT NOT NULL,
	CODIGOUNIDADE INT NOT NULL,
	DATACADASTRO DATETIME NOT NULL,
	DESCRICAOFUNCAO VARCHAR(60) NOT NULL,
	CONSTRAINT PK_CODIGOFUNCAO PRIMARY KEY (CODIGOFUNCAO),
)

CREATE TABLE ENDERECO (
	CODIGOENDERECO INT NOT NULL,
	CODIGOPESSOA INT NOT NULL,
	CODIGOUF INT NOT NULL,
	CODIGOMUNICIPIO INT NOT NULL,
	LOGRADOURO VARCHAR(60) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	BAIRRO VARCHAR(60) NOT NULL,
	COMPLEMENTO VARCHAR(50),	
	CEP VARCHAR (9), 	
	CONSTRAINT FK_CODIGOMUNICIPIO FOREIGN KEY (CODIGOMUNICIPIO) REFERENCES MUNICIPIO(CODIGOMUNICIPIO),
	CONSTRAINT FK_CODIGOUF FOREIGN KEY (CODIGOUF) REFERENCES UF(CODIGOUF),
	CONSTRAINT FK_CODIGOPESSOA FOREIGN KEY (CODIGOPESSOA) REFERENCES PESSOA(CODIGOPESSOA),
	CONSTRAINT PK_CODIGOENDERECO PRIMARY KEY (CODIGOENDERECO),
)

CREATE TABLE UF (
	CODIGOUF INT NOT NULL,	
	NOME VARCHAR(80) NOT NULL,
	CONSTRAINT PK_CODIGOENDERECO PRIMARY KEY (CODIGOUF),
)

ALTER TABLE UF
ADD SIGLA CHAR(2) 

ALTER TABLE MUNICIPIO
ADD  NOME VARCHAR(80) NOT NULL

CREATE TABLE MUNICIPIO (
	CODIGOMUNICIPIO INT NOT NULL,
	CODIGOUF INT NOT NULL,	
	NOME VARCHAR(80) NOT NULL,
	CONSTRAINT FK_CODIGOUF FOREIGN KEY (CODIGOUF) REFERENCES UF(CODIGOUF),
	CONSTRAINT PK_CODIGOMUNICIPIO PRIMARY KEY (CODIGOMUNICIPIO),
)

CREATE TABLE CLIENTE (
	CODIGOCLIENTE INT NOT NULL,	
	CODIGOPESSOA INT NOT NULL,
	CODIGOUSUARIO INT NOT NULL,
	DATAATUALIZACAO DATETIME NOT NULL,
	FIDELIDADE NUMERIC(15,2),	
	LIMITECREDITO NUMERIC(15,2),
	UTILIZALIMITECRED INT NOT NULL, 
	VALORPENDENTE NUMERIC(15,2),
	ULTIMACOMPRA DATETIME,
	INATIVO INT NOT NULL,
	OBSERVACOES VARCHAR (200), 
	CONSTRAINT FK_CODIGOPESSOA FOREIGN KEY (CODIGOPESSOA) REFERENCES PESSOA(CODIGOPESSOA),
	CONSTRAINT PK_CODIGOCLIENTE PRIMARY KEY (CODIGOCLIENTE),
)

CREATE TABLE PESSOA (
	CODIGOPESSOA INT NOT NULL,
	CODIGOENDERECO INT NOT NULL,
	CODIGOUSUARIO INT NOT NULL,
	CODIGOUNIDADE INT NOT NULL,
	NOME VARCHAR (50) NOT NULL,
	RAZAOSOCIAL VARCHAR (100),
	TIPOPESSOA CHAR NOT NULL,
	CPFCNPJ VARCHAR(18),
	RG varchar(10),
	SEXO CHAR NOT NULL,
	IDADE INT NOT NULL, 
	TELEFONEPRINCIPAL VARCHAR(11) NOT NULL, 
	TELEFONEOPCIONAL1 VARCHAR (11),
	TELEFONEOPCIONAL2 VARCHAR (11),
	DATACADASTRO DATE NOT NULL,
	EMAIL VARCHAR(80),
	FOTOPESSOA IMAGE,
	DATANASCIMENTO DATETIME,
	CONSTRAINT FK_CODIGOENDERECO FOREIGN KEY (CODIGOENDERECO) REFERENCES ENDERECO(CODIGOENDERECO),
	CONSTRAINT PK_CODIGOPESSOA PRIMARY KEY (CODIGOPESSOA),
)

CREATE TABLE LOGIN (
	CODIGOUSUARIO INT NOT NULL,
	USUARIO VARCHAR(50) NOT NULL,
	SENHA VARCHAR(70) NOT NULL,
	NIVELUSUARIO INT	
	CONSTRAINT PK_CODIGOUSUARIO PRIMARY KEY (CODIGOUSUARIO),
)

DROP TABLE LOGIN

CREATE TABLE ULTIMOACESSO (
	CODIGOUSUARIO INT NOT NULL,
	CODIGOUNIDADE INT NOT NULL,
	USUARIO VARCHAR(50) NOT NULL,
	DATAATUALIZACAO DATETIME NOT NULL,
	SENHA VARCHAR(70) NOT NULL,
	LEMBRARSENHA INT NOT NULL
	CONSTRAINT FK_CODIGOUSUARIO FOREIGN KEY (CODIGOUSUARIO) REFERENCES LOGIN(CODIGOUSUARIO)
)


DROP TABLE ULTIMOACESSO

SELECT * FROM ULTIMOACESSO


CREATE TABLE FORNECEDOR(
	CODIGOFORNECEDOR INT NOT NULL,
	CODIGOPESSOA INT NOT NULL,
	CODIGOUSUARIO INT NOT NULL,
	CODIGOESPECIALIDADE INT NOT NULL,
	CODIGOUNIDADE INT NOT NULL,
	DATACADASTRO DATE NOT NULL,
	NUMEROIE VARCHAR(12),
	OBSERVACOES VARCHAR (200), 
	CONSTRAINT FK_CODIGOESPECIALIDADE FOREIGN KEY (CODIGOESPECIALIDADE) REFERENCES ESPECIALIDADE(CODIGOESPECIALIDADE),
	CONSTRAINT FK_CODIGOPESSOA FOREIGN KEY (CODIGOPESSOA) REFERENCES PESSOA(CODIGOPESSOA),
	CONSTRAINT PK_CODIGOFORNECEDOR PRIMARY KEY(CODIGOFORNECEDOR),
)

CREATE TABLE SYSTEMCONFIG (
	CODIGOEMPRESA INT NOT NULL,
	NOMEEMPRESA VARCHAR(80) NOT NULL, 
	DATAIMPLANTACAO DATETIME NOT NULL,
	DATAEXPIRACAO DATETIME NOT NULL,
	ATIVO INT NOT NULL	
)

CREATE TABLE UNIDADE (
	CODIGOUNIDADE INT NOT NULL,
	NOMEUNIDADE VARCHAR(80) NOT NULL 	
)


INSERT INTO UNIDADE VALUES (1, 'Bicho Preguiça Pet Shop')





