USE [PetShop_Homologacao]
GO
/****** Object:  StoredProcedure [dbo].[SP_ALIMENTAULTIMOACESSO]    Script Date: 25/12/2016 23:12:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FC_VERIFICALICENCAEXPIRADA] (
	@CODIGOEMPRESA INT
)
RETURNS INT
AS
BEGIN 
	-- SE RETORNAR 1 É PQ A LICENÇA ESTÁ EXPIRADA
	IF (SELECT DATAEXPIRACAO FROM SYSTEMCONFIG WHERE CODIGOEMPRESA = @CODIGOEMPRESA) > GETDATE() 
	BEGIN
		RETURN 0 
	END

	RETURN 1
END;