--BUSCAR NOS OBJETOS DE BANCO O TEXTO 
	SELECT  DISTINCT
		CASE TYPE 
			WHEN 'TR' THEN OBJECT_NAME(SOB.parent_obj)
		ELSE 'Não se aplica'
		END AS 'TABELA ENVOLVIDA',
		SOB.NAME ,
		CASE TYPE WHEN 'P' THEN 'STORED PROCEDURE'
			WHEN 'FN' THEN 'FUNCTION'
			WHEN 'TF' THEN 'FUNCTION'
			WHEN 'TR' THEN 'TRIGGER'
			WHEN 'V' THEN 'VIEW'
		ELSE 'OUTROS OBJETOS' 
		END AS OBJETO
	FROM  SYSCOMMENTS SCM (NOLOCK)
		INNER JOIN SYSOBJECTS SOB (NOLOCK) ON SOB.ID = SCM.ID
	WHERE 
		SCM.TEXT LIKE '%TES_TITULOCONFERENCIA%'  
	ORDER BY 2 DESC