SELECT 
	T.NAME AS TABELA, 
	C.NAME AS COLUNA
FROM 
	SYS.SYSOBJECTS    AS T (NOLOCK) 
INNER JOIN SYS.ALL_COLUMNS AS C (NOLOCK) ON T.ID = C.OBJECT_ID AND T.XTYPE = 'U' 
WHERE 
	C.NAME LIKE '%CODIGOGRUPOHISTORICO%'
ORDER BY 
T.NAME ASC